#!/bin/bash
# SENTINEL-AI Enhanced Monitoring - Complete Test

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║     SENTINEL-AI Enhanced Monitoring - Complete Setup & Test     ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""

cd /home/kali/Documents/SENTINELAI-main

# Step 1: Verify components
echo "Step 1: Verifying components..."
cd server
python3 test_enhanced_monitoring.py
if [ $? -ne 0 ]; then
    echo "❌ Component verification failed"
    exit 1
fi
echo ""

# Step 2: Instructions
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                   SETUP COMPLETE - READY TO USE                  ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 TO SEE MONITORING IN ACTION:"
echo ""
echo "1️⃣  START THE SERVER (in this terminal):"
echo "    cd /home/kali/Documents/SENTINELAI-main/server"
echo "    python3 run_server.py"
echo ""
echo "    You will see:"
echo "    • Server startup messages"
echo "    • 'Enhanced Monitoring ACTIVE' message"
echo "    • Real-time activity display (updates every 30 seconds)"
echo ""
echo "2️⃣  SEND TEST SCANS (open NEW terminal, run):"
echo "    cd /home/kali/Documents/SENTINELAI-main"
echo "    python3 test_monitoring.py"
echo ""
echo "    This will send 5 test scans to the server"
echo ""
echo "3️⃣  WATCH YOUR SERVER TERMINAL:"
echo "    You'll see activity counters increase:"
echo "    📊 ACTIVITY STATISTICS:"
echo "      🔍 Threat Scans:           5"
echo "      🌐 Websites Monitored:     3"
echo "    "
echo "    🌐 Recent Websites (Last 5):"
echo "      • google.com [LOW]"
echo "      • github.com [LOW]"
echo "      • example.com [MEDIUM]"
echo ""
echo "4️⃣  CHECK DATABASE:"
echo "    cd server"
echo "    sqlite3 activity_monitoring.db \"SELECT * FROM threat_scans;\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚠️  IMPORTANT:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "The monitoring ONLY shows activity when scans are performed!"
echo ""
echo "Ways to generate activity:"
echo "  • Run test_monitoring.py (sends test scans)"
echo "  • Use the web UI (http://localhost:5000)"
echo "  • Send API requests manually"
echo "  • Use curl:"
echo "    curl -X POST http://localhost:5000/api/scan \\"
echo "         -H \"Content-Type: application/json\" \\"
echo "         -d '{\"type\": \"url\", \"target\": \"https://example.com\"}'"
echo ""
echo "Without scans, the terminal will show:"
echo "  📊 ACTIVITY STATISTICS:"
echo "    🌐 Websites Monitored:       0"
echo "    🔍 Threat Scans:              0"
echo "    ⚠️  Threats Detected:          0"
echo ""
echo "This is NORMAL - it means no activity yet!"
echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                      READY TO START!                             ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
